export const khodamNames: string[] = [
  "Kerbau",
  "Batman Maling Gas LPG",
  "Ular Berkepala Tiga",
  "Harimau Putih",
  "Naga Terbang",
  "Gajah Kecil",
  "Alien dari Planet Mars",
  "Serigala Hitam",
  "Kuda Poni",
  "Raja Hutan",
  "Si Monyet Lucu",
  "Burung Api",
  "Katak Berbisa",
  "Singa Laut",
  "Kucing Merah Jambu",
  "Tikus Berkacamata",
  "Paus Pembunuh",
  "Pinguin Raksasa",
  "Babi Terbang",
  "Kuda Laut",
  "Sapi Ungu",
  "Laba-Laba Besar",
  "Ikan Beracun",
  "Anjing Berbulu Emas",
  "Burung Hantu Bijak",
  "Kelinci Ajaib",
  "T-Rex Mini",
  "Dinosaurus Biru",
  "Zombie",
  "Vampir Malam",
  "Hantu Pocong",
  "Drakula",
  "Manusia Serigala",
  "Frankenstein",
  "Mumi Mesir",
  "Jin Botol",
  "Peri Kecil",
  "Ratu Salju",
  "Pangeran Katak",
  "Golem Batu",
  "Cyborg",
  "Robot Canggih",
  "Ninja Bayangan",
  "Samurai Kuno",
  "Ksatria Kegelapan",
  "Pahlawan Super",
  "Alien Hijau",
  "Astronot Terhilang",
  "Penjelajah Waktu",
  "Hantu Gentayangan",
  "Putri Duyung",
  "Dr. Monster",
  "Manusia Kelelawar",
  "Kucing Hutan",
  "Gorila Hitam",
  "Elang Emas",
  "Kuda Unicorn",
  "Harimau Merah",
  "Singa Emas",
  "Beruang Kutub",
  "Raksasa Hijau",
  "Perompak Laut",
  "Ratu Kegelapan",
  "Pangeran Cahaya",
  "Naga Api",
  "Naga Air",
  "Naga Udara",
  "Naga Tanah",
  "Makhluk Misterius",
  "Hantu Sungai",
  "Tikus Ajaib",
  "Kucing Ajaib",
  "Anjing Penjaga",
  "Burung Pelikan",
  "Buaya Sungai",
  "Ular Piton",
  "Gajah Merah",
  "Kucing Galaksi",
  "Makhluk Mars",
  "Makhluk Venus",
  "Hantu Rumah",
  "Hantu Kebun",
  "Hantu Laut",
  "Makhluk Dimensi Lain",
  "Penjaga Dimensi",
  "Pelindung Alam",
  "Ksatria Bintang",
  "Penunggang Naga",
  "Pemburu Harta",
  "Penjelajah Alam",
  "Penguasa Waktu",
  "Pencuri Hati",
  "Penyihir Hitam",
  "Penyihir Putih",
  "Dewi Bulan",
  "Dewa Matahari",
  "Penjaga Hutan",
  "Penguasa Laut",
  "Raja Gunung",
  "Ratu Padang Pasir",
  "Pahlawan Legenda",
  "Penguasa Angin",
  "Makhluk Gaib",
  "Naga Api Pemangsa",
  "Elf Penjaga Hutan",
  "Kurcaci Penambang",
  "Troll Pemakan Batu",
  "Goblin Pencuri Harta",
  "Pegasus Terbang Tinggi",
  "Griffin Penjaga Harta",
  "Phoenix Abadi",
  "Golem Besar",
  "Centaur Pemanah",
  "Werewolf Pemburu Malam",
  "Vampir Penghisap Darah",
  "Zombie Bangkit",
  "Siren Penggoda",
  "Dryad Penjaga Pohon",
  "Nymph Penari Air",
  "Mermaid Penyelam Dalam",
  "Cyclops Mata Satu",
  "Minotaur Labirin",
  "Kraken Penguasa Laut",
  "Banshee Pemberi Tanda",
  "Doppelganger Peniru",
  "Sphinx Pembuat Teka-Teki",
  "Chimera Berkepala Tiga",
  "Hydra Berleher Banyak",
  "Lich Raja Mati",
  "Drow Penyihir Kegelapan",
  "Ghoul Pemakan Bangkai",
  "Basilisk Penatap Mematikan",
  "Ifrit Api Menyala",
  "Djinn Pengabul Harapan",
  "Rakshasa Penjelmaan Iblis",
  "Kitsune Rubah Ajaib",
  "Tanuki Pengubah Bentuk",
  "Oni Raksasa Merah",
  "Yokai Hantu Jepang",
  "Wendigo Pemakan Manusia",
  "Chupacabra Penghisap Darah Kambing",
  "Fairy Kecil Bersayap",
  "Brownie Penjaga Rumah",
  "Leprechaun Penjaga Emas",
  "Selkie Manusia Anjing Laut",
  "Kelpie Kuda Air",
  "Tengu Pejuang Langit",
  "Dragonling Anak Naga",
  "Wyrm Ular Raksasa",
  "Cockatrice Penatap Batu",
  "Manticore Ekor Kalajengking",
  "Harpy Wanita Berbulu",
  "Faun Pemain Seruling",
  "Satyr Pemabuk",
  "Naiad Nimfa Air",
  "Sylph Nimfa Udara",
  "Gorgon Kepala Ular",
  "Medusa Penatap Batu",
  "Gryphon Raja Udara",
  "Wyvern Naga Kecil",
  "Jotunn Raksasa Es",
  "Efreet Raja Api",
  "Boggart Pengganggu Rumah",
  "Will-o'-the-wisp Penunjuk Jalan",
  "Barghest Anjing Neraka",
  "Hippogriff Bangsawan",
  "Nuckelavee Kuda Setan",
  "Basilisk Raja Ular",
  "Fenrir Serigala Raksasa",
  "Jormungandr Ular Dunia",
  "Sleipnir Kuda Delapan Kaki",
  "Fenris Penghancur Dunia",
  "Alkonost Burung Pemimpi",
  "Gamayun Burung Bijaksana",
  "Simurgh Burung Agung",
  "Ziz Burung Raksasa",
  "Anzu Burung Petir",
  "Garuda Penguasa Langit",
  "Naga Laut",
  "Leviathan Penguasa Laut",
  "Aspidochelone Kura-Kura Raksasa",
  "Bahamut Naga Emas",
  "Tiamat Naga Kepala Lima",
  "Fafnir Naga Serakah",
  "Ouroboros Ular Tak Berujung",
  "Ananta Shesha Ular Kosmik",
  "Quetzalcoatl Ular Berbulu",
  "Amphisbaena Ular Berkepala Dua",
  "Bicorn Kuda Bertanduk Dua",
  "Sleipnir Kuda Ajaib",
  "Tarrasque Monster Tak Terkalahkan",
  "Kirin Kuda Mistis",
  "Mokele-mbembe Dinosaurus Hidup",
  "Ogopogo Monster Danau",
  "Bunyip Monster Rawa",
  "Ahool Kelelawar Raksasa",
  "Dullahan Penunggang Tanpa Kepala",
  "Baba Yaga Penyihir Hutan",
  "Koschei Abadi",
  "Cernunnos Dewa Alam",
  "Morgana Le Fay Penyihir",
  "Merlin Penyihir Agung",
  "Pocong Penghuni Kuburan",
  "Kuntilanak Penunggu Pohon",
  "Genderuwo Penjaga Rumah Tua",
  "Wewe Gombel Penculik Anak",
  "Tuyul Pencuri Uang",
  "Sundel Bolong Penggoda Malam",
  "Leak Penjelmaan Iblis",
  "Banaspati Api Terbang",
  "Jenglot Makhluk Kerdil",
  "Palasik Pemakan Bayi",
  "Nyai Roro Kidul Ratu Pantai Selatan",
  "Suster Ngesot Penunggu Rumah Sakit",
  "Siluman Ular Penghuni Goa",
  "Begu Ganjang Penghisap Darah",
  "Hantu Jeruk Purut Penghuni Makam",
  "Hantu Tanjakan Pemburu Pengendara",
  "Suwanggi Penyihir Hitam",
  "Hantu Kopek Penarik Jiwa",
  "Nenek Gayung Pembawa Kematian",
  "Anak Bunian Makhluk Halus",
  "Hantu Air Penghuni Danau",
  "Hantu Belanda Penghuni Rumah Tua",
  "Hantu Kuburan Penunggu Malam",
  "Buto Ijo Raksasa Hijau",
  "Babi Ngepet Penjelmaan Setan",
  "Hantu Kepala Buntung Penguasa Kegelapan",
  "Hantu Pohon Beringin Penjaga Alam",
  "Kolor Ijo Pengintai Malam",
  "Hantu Gendong Pembawa Bencana",
  "Hantu Penanggalan Kepala Terbang",
  "Hantu Kereta Penghuni Rel",
  "Hantu Noni Belanda Penunggu Rumah Kolonial",
  "Hantu Merah Pembawa Petaka",
  "Hantu Hitam Penguasa Malam",
  "Hantu Poci Penunggu Tenda",
  "Hantu Long Bedugur Penunggu Rawa",
  "Hantu Jambon Penguasa Jembatan",
  "Hantu Busut Penunggu Bukit",
  "Hantu Malam Pengintai Gelap",
  "Hantu Dapur Penunggu Perapian",
  "Hantu Atap Penunggu Genteng",
  "Hantu Sumur Penghuni Sumur Tua",
  "Hantu Penjara Penguasa Sel",
  "Hantu Jalan Raya Pemburu Pengendara",
  "Hantu Bangku Kosong Penunggu Kelas",
  "Hantu Jendela Penunggu Rumah",
  "Hantu Angkot Penghuni Kendaraan",
  "Hantu Cermin Penunggu Bayangan",
  "Hantu Guling Penunggu Bantal",
  "Hantu Sawah Penguasa Ladang",
  "Hantu Penjaga Makam Tua",
  "Hantu Penjaga Jembatan Kecil",
  "Hantu Rumah Kosong Penghuni Bangunan",
  "Hantu Malam Jumat Penguasa Malam",
  "Hantu Penjaga Pantai Selatan",
  "Hantu Penjaga Gunung Berapi",
  "Hantu Penunggu Hutan",
  "Hantu Penunggu Kebun",
  "Hantu Sungai Penunggu Aliran Air",
  "Hantu Penunggu Gua Gelap",
  "Hantu Penunggu Pabrik Tua",
  "Hantu Penunggu Mall Kosong",
  "Hantu Penunggu Taman Kota",
  "Hantu Penunggu Pasar Malam",
  "Hantu Penunggu Bioskop",
  "Hantu Penunggu Toko Sepi",
  "Hantu Penunggu Warung Tua",
  "Hantu Penunggu Menara",
  "Hantu Penunggu Gedung Kosong",
  "Hantu Penunggu Jembatan Besi",
  "Hantu Penunggu Bendungan",
  "Hantu Penunggu Lapangan",
  "Hantu Penunggu Sekolah Malam",
  "Hantu Penunggu Rumah Sakit Jiwa",
  "Hantu Penunggu Asrama",
  "Hantu Penunggu Perpustakaan Tua",
  "Hantu Penunggu Taman Bermain",
  "Hantu Penunggu Kapal Tua",
  "Hantu Penunggu Dermaga Sepi",
  "Hantu Penunggu Garasi Tua",
  "Hantu Penunggu Terminal",
  "Hantu Penunggu Peron",
  "Hantu Penunggu Kuburan Cina",
  "Hantu Penunggu Perumahan Sepi",
  "Hantu Penunggu Kampus Tua",
  "Hantu Penunggu Museum",
  "Hantu Penunggu Kantor Lama",
  "Hantu Penunggu Lapangan Terbengkalai",
  "Hantu Penunggu Bandara Lama",
  "Hantu Penunggu Pelabuhan Tua",
  "Hantu Penunggu Rawa-Rawa",
  "Hantu Penunggu Kampung Terbengkalai",
  "Hantu Penunggu Pemakaman",
  "Hantu Penunggu Kolam Renang",
  "Hantu Penunggu Tepi Laut",
  "Hantu Penunggu Kamar Hotel Tua",
  "Hantu Penunggu Rumah Kayu",
  "Hantu Penunggu Lantai Atas",
  "Hantu Penunggu Lantai Bawah",
  "Hantu Penunggu Ruang Bawah Tanah"
];
