export const khodamNames: string[] = [
  "Kerbau",
  "Batman Maling Gas LPG",
  "Ular Berkepala Tiga",
  "Harimau Putih",
  "Naga Terbang",
  "Gajah Kecil",
  "Alien dari Planet Mars",
  "Serigala Hitam",
  "Kuda Poni",
  "Raja Hutan",
  "Si Monyet Lucu",
  "Burung Api",
  "Katak Berbisa",
  "Singa Laut",
  "Kucing Merah Jambu",
  "Tikus Berkacamata",
  "Paus Pembunuh",
  "Pinguin Raksasa",
  "Babi Terbang",
  "Kuda Laut",
  "Sapi Ungu",
  "Laba-Laba Besar",
  "Ikan Beracun",
  "Anjing Berbulu Emas",
  "Burung Hantu Bijak",
  "Kelinci Ajaib",
  "T-Rex Mini",
  "Dinosaurus Biru",
  "Zombie",
  "Vampir Malam",
  "Hantu Pocong",
  "Drakula",
  "Manusia Serigala",
  "Frankenstein",
  "Mumi Mesir",
  "Jin Botol",
  "Peri Kecil",
  "Ratu Salju",
  "Pangeran Katak",
  "Golem Batu",
  "Cyborg",
  "Robot Canggih",
  "Ninja Bayangan",
  "Samurai Kuno",
  "Ksatria Kegelapan",
  "Pahlawan Super",
  "Alien Hijau",
  "Astronot Terhilang",
  "Penjelajah Waktu",
  "Hantu Gentayangan",
  "Putri Duyung",
  "Dr. Monster",
  "Manusia Kelelawar",
  "Kucing Hutan",
  "Gorila Hitam",
  "Elang Emas",
  "Kuda Unicorn",
  "Harimau Merah",
  "Singa Emas",
  "Beruang Kutub",
  "Raksasa Hijau",
  "Perompak Laut",
  "Ratu Kegelapan",
  "Pangeran Cahaya",
  "Naga Api",
  "Naga Air",
  "Naga Udara",
  "Naga Tanah",
  "Makhluk Misterius",
  "Hantu Sungai",
  "Tikus Ajaib",
  "Kucing Ajaib",
  "Anjing Penjaga",
  "Burung Pelikan",
  "Buaya Sungai",
  "Ular Piton",
  "Gajah Merah",
  "Kucing Galaksi",
  "Makhluk Mars",
  "Makhluk Venus",
  "Hantu Rumah",
  "Hantu Kebun",
  "Hantu Laut",
  "Makhluk Dimensi Lain",
  "Penjaga Dimensi",
  "Pelindung Alam",
  "Ksatria Bintang",
  "Penunggang Naga",
  "Pemburu Harta",
  "Penjelajah Alam",
  "Penguasa Waktu",
  "Pencuri Hati",
  "Penyihir Hitam",
  "Penyihir Putih",
  "Dewi Bulan",
  "Dewa Matahari",
  "Penjaga Hutan",
  "Penguasa Laut",
  "Raja Gunung",
  "Ratu Padang Pasir",
  "Pahlawan Legenda",
  "Penguasa Angin",
  "Makhluk Gaib"
];
